package com.zhxx.service.szxt.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.AccessModelOptionEntity;
import com.zhxx.service.szxt.entity.AccessOptionEntity;
@Mapper
public interface AccessOptionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_option
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_option
     *
     * @mbg.generated
     */
    int insert(AccessOptionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_option
     *
     * @mbg.generated
     */
    int insertSelective(AccessOptionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_option
     *
     * @mbg.generated
     */
    AccessOptionEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccessOptionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccessOptionEntity record);
    
    List<AccessOptionEntity> queryAllOption(Map<String,String> map);
}