package com.zhxx.service.szxt.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.AccessModelEntity;
@Mapper
public interface AccessModelEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model
     *
     * @mbg.generated
     */
    int insert(AccessModelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model
     *
     * @mbg.generated
     */
    int insertSelective(AccessModelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model
     *
     * @mbg.generated
     */
    AccessModelEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccessModelEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccessModelEntity record);
}