package com.zhxx.service.szxt.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.AccessModelOptionEntity;
@Mapper
public interface AccessModelOptionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model_option
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model_option
     *
     * @mbg.generated
     */
    int insert(AccessModelOptionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model_option
     *
     * @mbg.generated
     */
    int insertSelective(AccessModelOptionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model_option
     *
     * @mbg.generated
     */
    AccessModelOptionEntity selectByPrimaryKey(String relateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccessModelOptionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_model_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccessModelOptionEntity record);
    
    List<AccessModelOptionEntity> queryall(Map<String,String> map);
}