package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.AnswerEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface AnswerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    int insert(AnswerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    int insertSelective(AnswerEntity record);


    int answerQuestion(@Param("list") List<AnswerEntity> list);
}