package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.AnswerEntity;
import com.zhxx.service.szxt.entity.DimensionRecordEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface DimensionRecordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dimension_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String dimensionRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dimension_record
     *
     * @mbg.generated
     */
    int insert(DimensionRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dimension_record
     *
     * @mbg.generated
     */
    int insertSelective(DimensionRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dimension_record
     *
     * @mbg.generated
     */
    DimensionRecordEntity selectByPrimaryKey(String dimensionRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dimension_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DimensionRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dimension_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DimensionRecordEntity record);


    List<DimensionRecordEntity> selectSum(@Param("list") List<AnswerEntity> list);


    int insertSum(@Param("list") List<DimensionRecordEntity> list);
}