package com.zhxx.service.szxt.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.GrowthPlanningEntity;
@Mapper
public interface GrowthPlanningEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_planning
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String planningId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_planning
     *
     * @mbg.generated
     */
    int insert(GrowthPlanningEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_planning
     *
     * @mbg.generated
     */
    int insertSelective(GrowthPlanningEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_planning
     *
     * @mbg.generated
     */
    GrowthPlanningEntity selectByPrimaryKey(String planningId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_planning
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GrowthPlanningEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_planning
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GrowthPlanningEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_planning
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GrowthPlanningEntity record);
}