package com.zhxx.service.szxt.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.GrowthOutputEntity;
@Mapper
public interface GrowthOutputEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_output
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_output
     *
     * @mbg.generated
     */
    int insert(GrowthOutputEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_output
     *
     * @mbg.generated
     */
    int insertSelective(GrowthOutputEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_output
     *
     * @mbg.generated
     */
    GrowthOutputEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_output
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GrowthOutputEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_output
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GrowthOutputEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_output
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GrowthOutputEntity record);
}