package com.zhxx.service.szxt.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.GrowthCommentOutputEntity;
@Mapper
public interface GrowthCommentOutputEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_comment_output
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String releteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_comment_output
     *
     * @mbg.generated
     */
    int insert(GrowthCommentOutputEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_comment_output
     *
     * @mbg.generated
     */
    int insertSelective(GrowthCommentOutputEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_comment_output
     *
     * @mbg.generated
     */
    GrowthCommentOutputEntity selectByPrimaryKey(String releteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_comment_output
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GrowthCommentOutputEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table growth_comment_output
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GrowthCommentOutputEntity record);
}