package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.ProblemEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ProblemEntityMapper {

    /**
     * 查询每种题的数量
     * by 王传营
     * @mbg.generated
     */
    List<ProblemEntity> selectDimension(ProblemEntity questionBankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String problemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated
     */
    int insert(ProblemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated
     */
    int insertSelective(ProblemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated
     */
    ProblemEntity selectByPrimaryKey(String problemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProblemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProblemEntity record);

    int insertList(@Param("list") List<ProblemEntity> problemEntityList);
}