package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.ProblemEntity;
import com.zhxx.service.szxt.entity.QuestionBankEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.awt.*;
import java.util.*;
import java.util.List;

@Mapper
@Repository
public interface QuestionBankEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_bank
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String questionBankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_bank
     *
     * @mbg.generated
     */
    int insert(QuestionBankEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_bank
     *
     * @mbg.generated
     */
    int insertSelective(QuestionBankEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_bank
     *
     * @mbg.generated
     */
    QuestionBankEntity selectByPrimaryKey(String questionBankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_bank
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestionBankEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_bank
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestionBankEntity record);

    //题库查询
    List<QuestionBankEntity> selectQuestionBank(QuestionBankEntity record);

    //添加题库
    int addQuestionBank(QuestionBankEntity record);

    //教师预览试题
    List<ProblemEntity> problemAndSolution(String record);

    List<QuestionBankEntity> selectByQuestionBankStage(Integer record);

    int updateQuestionStatus(QuestionBankEntity record);

}