package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.SolutionEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SolutionEntityMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbg.generated
     */
    List<SolutionEntity> selectFraction(SolutionEntity solutionEntity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String solutionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbg.generated
     */
    int insert(SolutionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbg.generated
     */
    int insertSelective(SolutionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbg.generated
     */
    SolutionEntity selectByPrimaryKey(String solutionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SolutionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SolutionEntity record);

    int insertList(@Param("list") List<SolutionEntity> solutionEntities);
}