package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.StageEntity;
import com.zhxx.service.szxt.entity.StageRecordEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface StageRecordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String stageRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_record
     *
     * @mbg.generated
     */
    int insert(StageRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_record
     *
     * @mbg.generated
     */
    int insertSelective(StageRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_record
     *
     * @mbg.generated
     */
    StageRecordEntity selectByPrimaryKey(String stageRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StageRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StageRecordEntity record);

    List<StageEntity> selectStageRecordAll(String taskRecordId);
}