package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.StageEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface StageEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String stageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int insert(StageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int insertSelective(StageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    StageEntity selectByPrimaryKey(String stageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StageEntity record);

    int deleteByTaskId(String record);

    List<StageEntity> selectStageAll(String taskId);  //查询任务下所有阶段

    List<StageEntity> selectStageEndBefore(String taskId);//查询任务下除了总结的所有阶段

}