package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.StudentChangeEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface StudentChangeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_change
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String studentChangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_change
     *
     * @mbg.generated
     */
    int insert(StudentChangeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_change
     *
     * @mbg.generated
     */
    int insertSelective(StudentChangeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_change
     *
     * @mbg.generated
     */
    StudentChangeEntity selectByPrimaryKey(String studentChangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_change
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StudentChangeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_change
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StudentChangeEntity record);

    List<StudentChangeEntity> selectStudentChange(String studentId);
}