package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.TaskRecordEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Mapper
@Repository
public interface TaskRecordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String taskRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated
     */
    int insert(TaskRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated
     */
    int insertSelective(TaskRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated
     */
    TaskRecordEntity selectByPrimaryKey(String taskRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskRecordEntity record);

    List<TaskRecordEntity> selectTaskState(String markId);

    TaskRecordEntity selectOneTaskRecord(TaskRecordEntity record);

    List<TaskRecordEntity> selectTaskAll(Map<String, Object> hashMap);

    int updateTaskRecordStatus();  //定时  任务过期修改

    int updateEndTaskRecordStatus();//定时  学生升学年后  没完成的任务会过期
}