package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.TaskEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface TaskEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int insert(TaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int insertSelective(TaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    TaskEntity selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskEntity record);

    List<TaskEntity> selectTaskList(String dimensionId);

    List<TaskEntity> selectUnpublishedTask(TaskEntity taskEntity);

    List<TaskEntity> selectUpTask(TaskEntity taskEntity);  //查询全部任务list

    int deleteUnpublishedTask(TaskEntity record);

    int updateUnpublishedTask(TaskEntity record);

    TaskEntity selectPcTask(String taskId);

    TaskEntity selectPcTaskCount(String taskId);
}
