package com.zhxx.service.szxt.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.TeacherRoleEntity;
@Mapper
public interface TeacherRoleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String teacherRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_role
     *
     * @mbg.generated
     */
    int insert(TeacherRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_role
     *
     * @mbg.generated
     */
    int insertSelective(TeacherRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_role
     *
     * @mbg.generated
     */
    TeacherRoleEntity selectByPrimaryKey(String teacherRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherRoleEntity record);
}