package com.zhxx.service.szxt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.TeacherAchievementsDictEntity;
@Mapper
public interface TeacherAchievementsDictEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_achievements_dict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_achievements_dict
     *
     * @mbg.generated
     */
    int insert(TeacherAchievementsDictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_achievements_dict
     *
     * @mbg.generated
     */
    int insertSelective(TeacherAchievementsDictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_achievements_dict
     *
     * @mbg.generated
     */
    TeacherAchievementsDictEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_achievements_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherAchievementsDictEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_achievements_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherAchievementsDictEntity record);
    
    List<TeacherAchievementsDictEntity> queryAchievementsDict(TeacherAchievementsDictEntity record);
}