package com.zhxx.service.szxt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.TeacherPaperEntity;
import com.zhxx.service.szxt.entity.TeacherUserEntity;
import com.zhxx.service.szxt.entity.TeacherWritingsEntity;
@Mapper
public interface TeacherWritingsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_writings
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_writings
     *
     * @mbg.generated
     */
    int insert(TeacherWritingsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_writings
     *
     * @mbg.generated
     */
    int insertSelective(TeacherWritingsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_writings
     *
     * @mbg.generated
     */
    TeacherWritingsEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_writings
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherWritingsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_writings
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherWritingsEntity record);



    TeacherWritingsEntity selectCom(TeacherWritingsEntity record);
    List<TeacherWritingsEntity> selectList(TeacherWritingsEntity record);
    List<TeacherWritingsEntity> queryForExcel(TeacherUserEntity record);
}