package com.zhxx.service.szxt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.StudentEntity;
import com.zhxx.service.szxt.entity.TeacherUserEntity;
@Mapper
public interface TeacherUserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String string);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_user
     *
     * @mbg.generated
     */
    int insert(TeacherUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_user
     *
     * @mbg.generated
     */
    int insertSelective(TeacherUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_user
     *
     * @mbg.generated
     */
    TeacherUserEntity selectByPrimaryKey(String teacherId);
    TeacherUserEntity selectOpenId(String teacherId);
    List<TeacherUserEntity> selectTeacherList(TeacherUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherUserEntity record);
    
    TeacherUserEntity selectByTeacherNo(String teacherNo);
    int updateByTeacherNo(TeacherUserEntity record);  
    List<TeacherUserEntity> selectTeacherOutput(TeacherUserEntity record);
    
   
}