package com.zhxx.service.szxt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.TeacherOutputPicRelateEntity;
@Mapper
public interface TeacherOutputPicRelateEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_output_pic_relate
     *
     * @mbg.generated
     */
    int insert(TeacherOutputPicRelateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_output_pic_relate
     *
     * @mbg.generated
     */
    int insertSelective(TeacherOutputPicRelateEntity record);
    
    int deleteByPrimaryKey(String str);
    
    List<TeacherOutputPicRelateEntity> selPic(TeacherOutputPicRelateEntity record);
}