package com.zhxx.service.szxt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.StudentEntity;
import com.zhxx.service.szxt.entity.TeacherStudentRelateEntity;
import com.zhxx.service.szxt.entity.TeacherUserEntity;
@Mapper
public interface TeacherStudentRelateEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student_relate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TeacherStudentRelateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student_relate
     *
     * @mbg.generated
     */
    int insert(TeacherStudentRelateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student_relate
     *
     * @mbg.generated
     */
    int insertSelective(TeacherStudentRelateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student_relate
     *
     * @mbg.generated
     */
    TeacherStudentRelateEntity selectByPrimaryKey(String teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student_relate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherStudentRelateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_student_relate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherStudentRelateEntity record);
    
    List<StudentEntity> bindStudentList(TeacherStudentRelateEntity record);
}