package com.zhxx.service.szxt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.TeacherConcludingEntity;
import com.zhxx.service.szxt.entity.TeacherPaperEntity;
import com.zhxx.service.szxt.entity.TeacherUserEntity;
@Mapper
public interface TeacherConcludingEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_concluding
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_concluding
     *
     * @mbg.generated
     */
    int insert(TeacherConcludingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_concluding
     *
     * @mbg.generated
     */
    int insertSelective(TeacherConcludingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_concluding
     *
     * @mbg.generated
     */
    TeacherConcludingEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_concluding
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherConcludingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_concluding
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherConcludingEntity record);
    
    List<TeacherConcludingEntity> selectList(TeacherConcludingEntity record);
    List<TeacherConcludingEntity> queryForExcel(TeacherUserEntity record);
}