package com.zhxx.service.szxt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.TeacherHorizontalEntity;
import com.zhxx.service.szxt.entity.TeacherPaperEntity;
import com.zhxx.service.szxt.entity.TeacherUserEntity;
@Mapper
public interface TeacherHorizontalEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_horizontal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_horizontal
     *
     * @mbg.generated
     */
    int insert(TeacherHorizontalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_horizontal
     *
     * @mbg.generated
     */
    int insertSelective(TeacherHorizontalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_horizontal
     *
     * @mbg.generated
     */
    TeacherHorizontalEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_horizontal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherHorizontalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_horizontal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherHorizontalEntity record);
    
    List<TeacherHorizontalEntity> selectList(TeacherHorizontalEntity record);
    List<TeacherHorizontalEntity> queryForExcel(TeacherUserEntity record);
}