package com.zhxx.service.szxt.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.zhxx.service.szxt.entity.TeacherPaperEntity;
import com.zhxx.service.szxt.entity.TeacherProjectEntity;
import com.zhxx.service.szxt.entity.TeacherUserEntity;
@Mapper
public interface TeacherProjectEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_project
     *
     * @mbg.generated
     */
    int insert(TeacherProjectEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_project
     *
     * @mbg.generated
     */
    int insertSelective(TeacherProjectEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_project
     *
     * @mbg.generated
     */
    TeacherProjectEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherProjectEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherProjectEntity record);
    
    List<TeacherProjectEntity> selectList(TeacherProjectEntity record);
    List<TeacherProjectEntity> queryForExcel(TeacherUserEntity record);
}