package com.zhxx.service.szxt.mapper;

import com.zhxx.service.szxt.entity.StudentEntity;
import com.zhxx.service.szxt.entity.WechatParentEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface WechatParentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_parent
     *
     * @mbg.generated
     */
    int insert(WechatParentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_parent
     *
     * @mbg.generated
     */
    int insertSelective(WechatParentEntity record);

    /**查询（可带条件）*/
    List< WechatParentEntity> selectBy(WechatParentEntity wechatParentEntity);

    /**根据openid删除*/
    void deletebinding (WechatParentEntity wechatParentEntity);

    /**关联学生表判断学号与绑定码*/
    List<WechatParentEntity> selectStudentNo(WechatParentEntity wechatParentEntity);

    /**
     * 查询是否存在
     * @param openId
     * @return
     */
    WechatParentEntity selectParent(String openId);
}