package com.zhxx.service.szxt.entity;

public class AccessOptionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_option.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_option.option_order
     *
     * @mbg.generated
     */
    private String optionOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_option.option_comment
     *
     * @mbg.generated
     */
    private String optionComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_option.option_score
     *
     * @mbg.generated
     */
    private String optionScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_option.standbyfield1
     *
     * @mbg.generated
     */
    private String standbyfield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_option.standbyfield2
     *
     * @mbg.generated
     */
    private String standbyfield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_option.standbyfield3
     *
     * @mbg.generated
     */
    private String standbyfield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_option.standbyfield4
     *
     * @mbg.generated
     */
    private String standbyfield4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_option.standbyfield5
     *
     * @mbg.generated
     */
    private String standbyfield5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_option.id
     *
     * @return the value of access_option.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_option.id
     *
     * @param id the value for access_option.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_option.option_order
     *
     * @return the value of access_option.option_order
     *
     * @mbg.generated
     */
    public String getOptionOrder() {
        return optionOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_option.option_order
     *
     * @param optionOrder the value for access_option.option_order
     *
     * @mbg.generated
     */
    public void setOptionOrder(String optionOrder) {
        this.optionOrder = optionOrder == null ? null : optionOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_option.option_comment
     *
     * @return the value of access_option.option_comment
     *
     * @mbg.generated
     */
    public String getOptionComment() {
        return optionComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_option.option_comment
     *
     * @param optionComment the value for access_option.option_comment
     *
     * @mbg.generated
     */
    public void setOptionComment(String optionComment) {
        this.optionComment = optionComment == null ? null : optionComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_option.option_score
     *
     * @return the value of access_option.option_score
     *
     * @mbg.generated
     */
    public String getOptionScore() {
        return optionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_option.option_score
     *
     * @param optionScore the value for access_option.option_score
     *
     * @mbg.generated
     */
    public void setOptionScore(String optionScore) {
        this.optionScore = optionScore == null ? null : optionScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_option.standbyfield1
     *
     * @return the value of access_option.standbyfield1
     *
     * @mbg.generated
     */
    public String getStandbyfield1() {
        return standbyfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_option.standbyfield1
     *
     * @param standbyfield1 the value for access_option.standbyfield1
     *
     * @mbg.generated
     */
    public void setStandbyfield1(String standbyfield1) {
        this.standbyfield1 = standbyfield1 == null ? null : standbyfield1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_option.standbyfield2
     *
     * @return the value of access_option.standbyfield2
     *
     * @mbg.generated
     */
    public String getStandbyfield2() {
        return standbyfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_option.standbyfield2
     *
     * @param standbyfield2 the value for access_option.standbyfield2
     *
     * @mbg.generated
     */
    public void setStandbyfield2(String standbyfield2) {
        this.standbyfield2 = standbyfield2 == null ? null : standbyfield2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_option.standbyfield3
     *
     * @return the value of access_option.standbyfield3
     *
     * @mbg.generated
     */
    public String getStandbyfield3() {
        return standbyfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_option.standbyfield3
     *
     * @param standbyfield3 the value for access_option.standbyfield3
     *
     * @mbg.generated
     */
    public void setStandbyfield3(String standbyfield3) {
        this.standbyfield3 = standbyfield3 == null ? null : standbyfield3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_option.standbyfield4
     *
     * @return the value of access_option.standbyfield4
     *
     * @mbg.generated
     */
    public String getStandbyfield4() {
        return standbyfield4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_option.standbyfield4
     *
     * @param standbyfield4 the value for access_option.standbyfield4
     *
     * @mbg.generated
     */
    public void setStandbyfield4(String standbyfield4) {
        this.standbyfield4 = standbyfield4 == null ? null : standbyfield4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_option.standbyfield5
     *
     * @return the value of access_option.standbyfield5
     *
     * @mbg.generated
     */
    public String getStandbyfield5() {
        return standbyfield5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_option.standbyfield5
     *
     * @param standbyfield5 the value for access_option.standbyfield5
     *
     * @mbg.generated
     */
    public void setStandbyfield5(String standbyfield5) {
        this.standbyfield5 = standbyfield5 == null ? null : standbyfield5.trim();
    }
}