package com.zhxx.service.szxt.entity;

import java.util.Date;

public class AccessModelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.applicablegrade
     *
     * @mbg.generated
     */
    private String applicablegrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.modelLevel
     *
     * @mbg.generated
     */
    private String modellevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.required
     *
     * @mbg.generated
     */
    private String required;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.open_close_state
     *
     * @mbg.generated
     */
    private String openCloseState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.standbyfield1
     *
     * @mbg.generated
     */
    private String standbyfield1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.standbyfield2
     *
     * @mbg.generated
     */
    private String standbyfield2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.standbyfield3
     *
     * @mbg.generated
     */
    private String standbyfield3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.standbyfield4
     *
     * @mbg.generated
     */
    private String standbyfield4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.standbyfield5
     *
     * @mbg.generated
     */
    private String standbyfield5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.lastoperator
     *
     * @mbg.generated
     */
    private String lastoperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.id
     *
     * @return the value of access_model.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.id
     *
     * @param id the value for access_model.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.title
     *
     * @return the value of access_model.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.title
     *
     * @param title the value for access_model.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.description
     *
     * @return the value of access_model.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.description
     *
     * @param description the value for access_model.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.applicablegrade
     *
     * @return the value of access_model.applicablegrade
     *
     * @mbg.generated
     */
    public String getApplicablegrade() {
        return applicablegrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.applicablegrade
     *
     * @param applicablegrade the value for access_model.applicablegrade
     *
     * @mbg.generated
     */
    public void setApplicablegrade(String applicablegrade) {
        this.applicablegrade = applicablegrade == null ? null : applicablegrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.category
     *
     * @return the value of access_model.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.category
     *
     * @param category the value for access_model.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.modelLevel
     *
     * @return the value of access_model.modelLevel
     *
     * @mbg.generated
     */
    public String getModellevel() {
        return modellevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.modelLevel
     *
     * @param modellevel the value for access_model.modelLevel
     *
     * @mbg.generated
     */
    public void setModellevel(String modellevel) {
        this.modellevel = modellevel == null ? null : modellevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.required
     *
     * @return the value of access_model.required
     *
     * @mbg.generated
     */
    public String getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.required
     *
     * @param required the value for access_model.required
     *
     * @mbg.generated
     */
    public void setRequired(String required) {
        this.required = required == null ? null : required.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.open_close_state
     *
     * @return the value of access_model.open_close_state
     *
     * @mbg.generated
     */
    public String getOpenCloseState() {
        return openCloseState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.open_close_state
     *
     * @param openCloseState the value for access_model.open_close_state
     *
     * @mbg.generated
     */
    public void setOpenCloseState(String openCloseState) {
        this.openCloseState = openCloseState == null ? null : openCloseState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.standbyfield1
     *
     * @return the value of access_model.standbyfield1
     *
     * @mbg.generated
     */
    public String getStandbyfield1() {
        return standbyfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.standbyfield1
     *
     * @param standbyfield1 the value for access_model.standbyfield1
     *
     * @mbg.generated
     */
    public void setStandbyfield1(String standbyfield1) {
        this.standbyfield1 = standbyfield1 == null ? null : standbyfield1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.standbyfield2
     *
     * @return the value of access_model.standbyfield2
     *
     * @mbg.generated
     */
    public String getStandbyfield2() {
        return standbyfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.standbyfield2
     *
     * @param standbyfield2 the value for access_model.standbyfield2
     *
     * @mbg.generated
     */
    public void setStandbyfield2(String standbyfield2) {
        this.standbyfield2 = standbyfield2 == null ? null : standbyfield2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.standbyfield3
     *
     * @return the value of access_model.standbyfield3
     *
     * @mbg.generated
     */
    public String getStandbyfield3() {
        return standbyfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.standbyfield3
     *
     * @param standbyfield3 the value for access_model.standbyfield3
     *
     * @mbg.generated
     */
    public void setStandbyfield3(String standbyfield3) {
        this.standbyfield3 = standbyfield3 == null ? null : standbyfield3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.standbyfield4
     *
     * @return the value of access_model.standbyfield4
     *
     * @mbg.generated
     */
    public String getStandbyfield4() {
        return standbyfield4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.standbyfield4
     *
     * @param standbyfield4 the value for access_model.standbyfield4
     *
     * @mbg.generated
     */
    public void setStandbyfield4(String standbyfield4) {
        this.standbyfield4 = standbyfield4 == null ? null : standbyfield4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.standbyfield5
     *
     * @return the value of access_model.standbyfield5
     *
     * @mbg.generated
     */
    public String getStandbyfield5() {
        return standbyfield5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.standbyfield5
     *
     * @param standbyfield5 the value for access_model.standbyfield5
     *
     * @mbg.generated
     */
    public void setStandbyfield5(String standbyfield5) {
        this.standbyfield5 = standbyfield5 == null ? null : standbyfield5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.state
     *
     * @return the value of access_model.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.state
     *
     * @param state the value for access_model.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.createtime
     *
     * @return the value of access_model.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.createtime
     *
     * @param createtime the value for access_model.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.updatetime
     *
     * @return the value of access_model.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.updatetime
     *
     * @param updatetime the value for access_model.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.lastoperator
     *
     * @return the value of access_model.lastoperator
     *
     * @mbg.generated
     */
    public String getLastoperator() {
        return lastoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.lastoperator
     *
     * @param lastoperator the value for access_model.lastoperator
     *
     * @mbg.generated
     */
    public void setLastoperator(String lastoperator) {
        this.lastoperator = lastoperator == null ? null : lastoperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model.operator
     *
     * @return the value of access_model.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model.operator
     *
     * @param operator the value for access_model.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}