package com.zhxx.service.szxt.entity;

public class AccessModelOptionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model_option.relate_id
     *
     * @mbg.generated
     */
    private String relateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model_option.model_id
     *
     * @mbg.generated
     */
    private String modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_model_option.option_id
     *
     * @mbg.generated
     */
    private String optionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model_option.relate_id
     *
     * @return the value of access_model_option.relate_id
     *
     * @mbg.generated
     */
    public String getRelateId() {
        return relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model_option.relate_id
     *
     * @param relateId the value for access_model_option.relate_id
     *
     * @mbg.generated
     */
    public void setRelateId(String relateId) {
        this.relateId = relateId == null ? null : relateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model_option.model_id
     *
     * @return the value of access_model_option.model_id
     *
     * @mbg.generated
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model_option.model_id
     *
     * @param modelId the value for access_model_option.model_id
     *
     * @mbg.generated
     */
    public void setModelId(String modelId) {
        this.modelId = modelId == null ? null : modelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_model_option.option_id
     *
     * @return the value of access_model_option.option_id
     *
     * @mbg.generated
     */
    public String getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_model_option.option_id
     *
     * @param optionId the value for access_model_option.option_id
     *
     * @mbg.generated
     */
    public void setOptionId(String optionId) {
        this.optionId = optionId == null ? null : optionId.trim();
    }
}