package com.zhxx.service.szxt.entity;

import java.util.Date;

public class AnswerEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answer_id
     *
     * @mbg.generated
     */
    private String answerId;


    private String studentId;

    private String solutionContent;

    private String solutionIds;

    public String getSolutionIds() {
        return solutionIds;
    }

    public void setSolutionIds(String solutionIds) {
        this.solutionIds = solutionIds;
    }

    public String getSolutionContent() {
        return solutionContent;
    }

    public void setSolutionContent(String solutionContent) {
        this.solutionContent = solutionContent;
    }

    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getQuestionId() {
        return questionId;
    }

    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }

    private String questionId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.problem_id
     *
     * @mbg.generated
     */
    private String problemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.solution_id
     *
     * @mbg.generated
     */
    private String solutionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.mark_id
     *
     * @mbg.generated
     */
    private String markId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answer_id
     *
     * @return the value of answer.answer_id
     * @mbg.generated
     */
    public String getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answer_id
     *
     * @param answerId the value for answer.answer_id
     * @mbg.generated
     */
    public void setAnswerId(String answerId) {
        this.answerId = answerId == null ? null : answerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.problem_id
     *
     * @return the value of answer.problem_id
     * @mbg.generated
     */
    public String getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.problem_id
     *
     * @param problemId the value for answer.problem_id
     * @mbg.generated
     */
    public void setProblemId(String problemId) {
        this.problemId = problemId == null ? null : problemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.solution_id
     *
     * @return the value of answer.solution_id
     * @mbg.generated
     */
    public String getSolutionId() {
        return solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.solution_id
     *
     * @param solutionId the value for answer.solution_id
     * @mbg.generated
     */
    public void setSolutionId(String solutionId) {
        this.solutionId = solutionId == null ? null : solutionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.mark_id
     *
     * @return the value of answer.mark_id
     * @mbg.generated
     */
    public String getMarkId() {
        return markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.mark_id
     *
     * @param markId the value for answer.mark_id
     * @mbg.generated
     */
    public void setMarkId(String markId) {
        this.markId = markId == null ? null : markId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.create_time
     *
     * @return the value of answer.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.create_time
     *
     * @param createTime the value for answer.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.modify_time
     *
     * @return the value of answer.modify_time
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.modify_time
     *
     * @param modifyTime the value for answer.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.status
     *
     * @return the value of answer.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.status
     *
     * @param status the value for answer.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}