package com.zhxx.service.szxt.entity;

import java.util.Date;

public class GrowthPlanningEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning.planning_id
     *
     * @mbg.generated
     */
    private String planningId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning.studen_id
     *
     * @mbg.generated
     */
    private String studenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning.studen_grade
     *
     * @mbg.generated
     */
    private String studenGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning.comment_person_id
     *
     * @mbg.generated
     */
    private String commentPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning.finishtime
     *
     * @mbg.generated
     */
    private Date finishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning.comment_comtent
     *
     * @mbg.generated
     */
    private String commentComtent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning.planning_id
     *
     * @return the value of growth_planning.planning_id
     *
     * @mbg.generated
     */
    public String getPlanningId() {
        return planningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning.planning_id
     *
     * @param planningId the value for growth_planning.planning_id
     *
     * @mbg.generated
     */
    public void setPlanningId(String planningId) {
        this.planningId = planningId == null ? null : planningId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning.studen_id
     *
     * @return the value of growth_planning.studen_id
     *
     * @mbg.generated
     */
    public String getStudenId() {
        return studenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning.studen_id
     *
     * @param studenId the value for growth_planning.studen_id
     *
     * @mbg.generated
     */
    public void setStudenId(String studenId) {
        this.studenId = studenId == null ? null : studenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning.studen_grade
     *
     * @return the value of growth_planning.studen_grade
     *
     * @mbg.generated
     */
    public String getStudenGrade() {
        return studenGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning.studen_grade
     *
     * @param studenGrade the value for growth_planning.studen_grade
     *
     * @mbg.generated
     */
    public void setStudenGrade(String studenGrade) {
        this.studenGrade = studenGrade == null ? null : studenGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning.comment_person_id
     *
     * @return the value of growth_planning.comment_person_id
     *
     * @mbg.generated
     */
    public String getCommentPersonId() {
        return commentPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning.comment_person_id
     *
     * @param commentPersonId the value for growth_planning.comment_person_id
     *
     * @mbg.generated
     */
    public void setCommentPersonId(String commentPersonId) {
        this.commentPersonId = commentPersonId == null ? null : commentPersonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning.finishtime
     *
     * @return the value of growth_planning.finishtime
     *
     * @mbg.generated
     */
    public Date getFinishtime() {
        return finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning.finishtime
     *
     * @param finishtime the value for growth_planning.finishtime
     *
     * @mbg.generated
     */
    public void setFinishtime(Date finishtime) {
        this.finishtime = finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning.createtime
     *
     * @return the value of growth_planning.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning.createtime
     *
     * @param createtime the value for growth_planning.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning.updatetime
     *
     * @return the value of growth_planning.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning.updatetime
     *
     * @param updatetime the value for growth_planning.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning.comment_comtent
     *
     * @return the value of growth_planning.comment_comtent
     *
     * @mbg.generated
     */
    public String getCommentComtent() {
        return commentComtent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning.comment_comtent
     *
     * @param commentComtent the value for growth_planning.comment_comtent
     *
     * @mbg.generated
     */
    public void setCommentComtent(String commentComtent) {
        this.commentComtent = commentComtent == null ? null : commentComtent.trim();
    }
}