package com.zhxx.service.szxt.entity;

public class GrowthCommentOutputEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_comment_output.relete_id
     *
     * @mbg.generated
     */
    private String releteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_comment_output.growth_comment_id
     *
     * @mbg.generated
     */
    private String growthCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_comment_output.output_id
     *
     * @mbg.generated
     */
    private String outputId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_comment_output.relete_id
     *
     * @return the value of growth_comment_output.relete_id
     *
     * @mbg.generated
     */
    public String getReleteId() {
        return releteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_comment_output.relete_id
     *
     * @param releteId the value for growth_comment_output.relete_id
     *
     * @mbg.generated
     */
    public void setReleteId(String releteId) {
        this.releteId = releteId == null ? null : releteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_comment_output.growth_comment_id
     *
     * @return the value of growth_comment_output.growth_comment_id
     *
     * @mbg.generated
     */
    public String getGrowthCommentId() {
        return growthCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_comment_output.growth_comment_id
     *
     * @param growthCommentId the value for growth_comment_output.growth_comment_id
     *
     * @mbg.generated
     */
    public void setGrowthCommentId(String growthCommentId) {
        this.growthCommentId = growthCommentId == null ? null : growthCommentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_comment_output.output_id
     *
     * @return the value of growth_comment_output.output_id
     *
     * @mbg.generated
     */
    public String getOutputId() {
        return outputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_comment_output.output_id
     *
     * @param outputId the value for growth_comment_output.output_id
     *
     * @mbg.generated
     */
    public void setOutputId(String outputId) {
        this.outputId = outputId == null ? null : outputId.trim();
    }
}