package com.zhxx.service.szxt.entity;

import java.util.Date;

public class GrowthPlanningCommentEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.planning_id
     *
     * @mbg.generated
     */
    private String planningId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.model_id
     *
     * @mbg.generated
     */
    private String modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.option_id
     *
     * @mbg.generated
     */
    private String optionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.finish_state
     *
     * @mbg.generated
     */
    private String finishState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.submit_state
     *
     * @mbg.generated
     */
    private String submitState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.model_title
     *
     * @mbg.generated
     */
    private String modelTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.model_desc
     *
     * @mbg.generated
     */
    private String modelDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.model_category
     *
     * @mbg.generated
     */
    private String modelCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.model_modellevel
     *
     * @mbg.generated
     */
    private String modelModellevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.option_comment
     *
     * @mbg.generated
     */
    private String optionComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.option_order
     *
     * @mbg.generated
     */
    private String optionOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_planning_comment.option_score
     *
     * @mbg.generated
     */
    private String optionScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.id
     *
     * @return the value of growth_planning_comment.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.id
     *
     * @param id the value for growth_planning_comment.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.planning_id
     *
     * @return the value of growth_planning_comment.planning_id
     *
     * @mbg.generated
     */
    public String getPlanningId() {
        return planningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.planning_id
     *
     * @param planningId the value for growth_planning_comment.planning_id
     *
     * @mbg.generated
     */
    public void setPlanningId(String planningId) {
        this.planningId = planningId == null ? null : planningId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.model_id
     *
     * @return the value of growth_planning_comment.model_id
     *
     * @mbg.generated
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.model_id
     *
     * @param modelId the value for growth_planning_comment.model_id
     *
     * @mbg.generated
     */
    public void setModelId(String modelId) {
        this.modelId = modelId == null ? null : modelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.option_id
     *
     * @return the value of growth_planning_comment.option_id
     *
     * @mbg.generated
     */
    public String getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.option_id
     *
     * @param optionId the value for growth_planning_comment.option_id
     *
     * @mbg.generated
     */
    public void setOptionId(String optionId) {
        this.optionId = optionId == null ? null : optionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.finish_state
     *
     * @return the value of growth_planning_comment.finish_state
     *
     * @mbg.generated
     */
    public String getFinishState() {
        return finishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.finish_state
     *
     * @param finishState the value for growth_planning_comment.finish_state
     *
     * @mbg.generated
     */
    public void setFinishState(String finishState) {
        this.finishState = finishState == null ? null : finishState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.submit_state
     *
     * @return the value of growth_planning_comment.submit_state
     *
     * @mbg.generated
     */
    public String getSubmitState() {
        return submitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.submit_state
     *
     * @param submitState the value for growth_planning_comment.submit_state
     *
     * @mbg.generated
     */
    public void setSubmitState(String submitState) {
        this.submitState = submitState == null ? null : submitState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.createtime
     *
     * @return the value of growth_planning_comment.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.createtime
     *
     * @param createtime the value for growth_planning_comment.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.updatetime
     *
     * @return the value of growth_planning_comment.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.updatetime
     *
     * @param updatetime the value for growth_planning_comment.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.model_title
     *
     * @return the value of growth_planning_comment.model_title
     *
     * @mbg.generated
     */
    public String getModelTitle() {
        return modelTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.model_title
     *
     * @param modelTitle the value for growth_planning_comment.model_title
     *
     * @mbg.generated
     */
    public void setModelTitle(String modelTitle) {
        this.modelTitle = modelTitle == null ? null : modelTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.model_desc
     *
     * @return the value of growth_planning_comment.model_desc
     *
     * @mbg.generated
     */
    public String getModelDesc() {
        return modelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.model_desc
     *
     * @param modelDesc the value for growth_planning_comment.model_desc
     *
     * @mbg.generated
     */
    public void setModelDesc(String modelDesc) {
        this.modelDesc = modelDesc == null ? null : modelDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.model_category
     *
     * @return the value of growth_planning_comment.model_category
     *
     * @mbg.generated
     */
    public String getModelCategory() {
        return modelCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.model_category
     *
     * @param modelCategory the value for growth_planning_comment.model_category
     *
     * @mbg.generated
     */
    public void setModelCategory(String modelCategory) {
        this.modelCategory = modelCategory == null ? null : modelCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.model_modellevel
     *
     * @return the value of growth_planning_comment.model_modellevel
     *
     * @mbg.generated
     */
    public String getModelModellevel() {
        return modelModellevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.model_modellevel
     *
     * @param modelModellevel the value for growth_planning_comment.model_modellevel
     *
     * @mbg.generated
     */
    public void setModelModellevel(String modelModellevel) {
        this.modelModellevel = modelModellevel == null ? null : modelModellevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.option_comment
     *
     * @return the value of growth_planning_comment.option_comment
     *
     * @mbg.generated
     */
    public String getOptionComment() {
        return optionComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.option_comment
     *
     * @param optionComment the value for growth_planning_comment.option_comment
     *
     * @mbg.generated
     */
    public void setOptionComment(String optionComment) {
        this.optionComment = optionComment == null ? null : optionComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.option_order
     *
     * @return the value of growth_planning_comment.option_order
     *
     * @mbg.generated
     */
    public String getOptionOrder() {
        return optionOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.option_order
     *
     * @param optionOrder the value for growth_planning_comment.option_order
     *
     * @mbg.generated
     */
    public void setOptionOrder(String optionOrder) {
        this.optionOrder = optionOrder == null ? null : optionOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_planning_comment.option_score
     *
     * @return the value of growth_planning_comment.option_score
     *
     * @mbg.generated
     */
    public String getOptionScore() {
        return optionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_planning_comment.option_score
     *
     * @param optionScore the value for growth_planning_comment.option_score
     *
     * @mbg.generated
     */
    public void setOptionScore(String optionScore) {
        this.optionScore = optionScore == null ? null : optionScore.trim();
    }
}