package com.zhxx.service.szxt.entity;

import java.util.Date;

public class GrowthOutputEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_output.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_output.output_type
     *
     * @mbg.generated
     */
    private String outputType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_output.output_url
     *
     * @mbg.generated
     */
    private String outputUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_output.output_upload_time
     *
     * @mbg.generated
     */
    private Date outputUploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_output.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_output.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column growth_output.output_url_comtent
     *
     * @mbg.generated
     */
    private String outputUrlComtent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_output.id
     *
     * @return the value of growth_output.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_output.id
     *
     * @param id the value for growth_output.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_output.output_type
     *
     * @return the value of growth_output.output_type
     *
     * @mbg.generated
     */
    public String getOutputType() {
        return outputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_output.output_type
     *
     * @param outputType the value for growth_output.output_type
     *
     * @mbg.generated
     */
    public void setOutputType(String outputType) {
        this.outputType = outputType == null ? null : outputType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_output.output_url
     *
     * @return the value of growth_output.output_url
     *
     * @mbg.generated
     */
    public String getOutputUrl() {
        return outputUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_output.output_url
     *
     * @param outputUrl the value for growth_output.output_url
     *
     * @mbg.generated
     */
    public void setOutputUrl(String outputUrl) {
        this.outputUrl = outputUrl == null ? null : outputUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_output.output_upload_time
     *
     * @return the value of growth_output.output_upload_time
     *
     * @mbg.generated
     */
    public Date getOutputUploadTime() {
        return outputUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_output.output_upload_time
     *
     * @param outputUploadTime the value for growth_output.output_upload_time
     *
     * @mbg.generated
     */
    public void setOutputUploadTime(Date outputUploadTime) {
        this.outputUploadTime = outputUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_output.createtime
     *
     * @return the value of growth_output.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_output.createtime
     *
     * @param createtime the value for growth_output.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_output.updatetime
     *
     * @return the value of growth_output.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_output.updatetime
     *
     * @param updatetime the value for growth_output.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column growth_output.output_url_comtent
     *
     * @return the value of growth_output.output_url_comtent
     *
     * @mbg.generated
     */
    public String getOutputUrlComtent() {
        return outputUrlComtent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column growth_output.output_url_comtent
     *
     * @param outputUrlComtent the value for growth_output.output_url_comtent
     *
     * @mbg.generated
     */
    public void setOutputUrlComtent(String outputUrlComtent) {
        this.outputUrlComtent = outputUrlComtent == null ? null : outputUrlComtent.trim();
    }
}