package com.zhxx.service.szxt.entity;

import java.util.Date;
import java.util.List;

public class MarkEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.mark_id
     *
     * @mbg.generated
     */
    private String markId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.mark_content
     *
     * @mbg.generated
     */
    private String markContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.dimension_id
     *
     * @mbg.generated
     */
    private String dimensionId;

    public String getDimensionName() {
        return dimensionName;
    }

    public void setDimensionName(String dimensionName) {
        this.dimensionName = dimensionName;
    }

    private String dimensionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.grade_evaluation_id
     *
     * @mbg.generated
     */
    private String gradeEvaluationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.sys_content
     *
     * @mbg.generated
     */
    private String sysContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.status
     *
     * @mbg.generated
     */
    private Integer status;

    private List<MarkEntity> Marklist;

    private List<DimensionRecordEntity> DimensionRecordEntity;

    public List<MarkEntity> getMarklist() {
        return Marklist;
    }

    public void setMarklist(List<MarkEntity> marklist) {
        Marklist = marklist;
    }

    public List<com.zhxx.service.szxt.entity.DimensionRecordEntity> getDimensionRecordEntity() {
        return DimensionRecordEntity;
    }

    public void setDimensionRecordEntity(List<com.zhxx.service.szxt.entity.DimensionRecordEntity> dimensionRecordEntity) {
        DimensionRecordEntity = dimensionRecordEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.mark_id
     *
     * @return the value of mark.mark_id
     * @mbg.generated
     */
    public String getMarkId() {
        return markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.mark_id
     *
     * @param markId the value for mark.mark_id
     * @mbg.generated
     */
    public void setMarkId(String markId) {
        this.markId = markId == null ? null : markId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.student_id
     *
     * @return the value of mark.student_id
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.student_id
     *
     * @param studentId the value for mark.student_id
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.user_id
     *
     * @return the value of mark.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.user_id
     *
     * @param userId the value for mark.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.mark_content
     *
     * @return the value of mark.mark_content
     * @mbg.generated
     */
    public String getMarkContent() {
        return markContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.mark_content
     *
     * @param markContent the value for mark.mark_content
     * @mbg.generated
     */
    public void setMarkContent(String markContent) {
        this.markContent = markContent == null ? null : markContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.dimension_id
     *
     * @return the value of mark.dimension_id
     * @mbg.generated
     */
    public String getDimensionId() {
        return dimensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.dimension_id
     *
     * @param dimensionId the value for mark.dimension_id
     * @mbg.generated
     */
    public void setDimensionId(String dimensionId) {
        this.dimensionId = dimensionId == null ? null : dimensionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.grade_evaluation_id
     *
     * @return the value of mark.grade_evaluation_id
     * @mbg.generated
     */
    public String getGradeEvaluationId() {
        return gradeEvaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.grade_evaluation_id
     *
     * @param gradeEvaluationId the value for mark.grade_evaluation_id
     * @mbg.generated
     */
    public void setGradeEvaluationId(String gradeEvaluationId) {
        this.gradeEvaluationId = gradeEvaluationId == null ? null : gradeEvaluationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.sys_content
     *
     * @return the value of mark.sys_content
     * @mbg.generated
     */
    public String getSysContent() {
        return sysContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.sys_content
     *
     * @param sysContent the value for mark.sys_content
     * @mbg.generated
     */
    public void setSysContent(String sysContent) {
        this.sysContent = sysContent == null ? null : sysContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.create_time
     *
     * @return the value of mark.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.create_time
     *
     * @param createTime the value for mark.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.modify_time
     *
     * @return the value of mark.modify_time
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.modify_time
     *
     * @param modifyTime the value for mark.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.status
     *
     * @return the value of mark.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.status
     *
     * @param status the value for mark.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    private List<StudentEntity> studentEntity;

    public List<StudentEntity> getStudentEntity() {
        return studentEntity;
    }

    public void setStudentEntity(List<StudentEntity> studentEntity) {
        this.studentEntity = studentEntity;
    }

    private List<GradeEvaluationEntity> gradeEvaluationEntity;

    public List<GradeEvaluationEntity> getGradeEvaluationEntity() {
        return gradeEvaluationEntity;
    }

    public void setGradeEvaluationEntity(List<GradeEvaluationEntity> gradeEvaluationEntity) {
        this.gradeEvaluationEntity = gradeEvaluationEntity;
    }

    private List<AnswerEntity> answerEntity;

    public List<AnswerEntity> getAnswerEntity() {
        return answerEntity;
    }

    public void setAnswerEntity(List<AnswerEntity> answerEntity) {
        this.answerEntity = answerEntity;
    }

}