package com.zhxx.service.szxt.entity;

import java.util.Date;
import java.util.List;

public class ProblemEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem_id
     *
     * @mbg.generated
     */
    private String problemId;

    private String questionBankName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.question_bank_id
     *
     * @mbg.generated
     */
    private String questionBankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem_title
     *
     * @mbg.generated
     */
    private String problemTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem_dimension
     *
     * @mbg.generated
     */
    private String problemDimension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.status
     *
     * @mbg.generated
     */
    private Integer status;

    private int sum; //问题的数量

    private List<AnswerEntity> answers;

    private List<SolutionEntity> solutionEntities;

    public int getSum() {
        return sum;
    }

    public void setSum(int sum) {
        this.sum = sum;
    }

    public List<SolutionEntity> getSolutionEntities() {
        return solutionEntities;
    }

    public void setSolutionEntities(List<SolutionEntity> solutionEntities) {
        this.solutionEntities = solutionEntities;
    }

    public String getQuestionBankName() {
        return questionBankName;
    }

    public void setQuestionBankName(String questionBankName) {
        this.questionBankName = questionBankName;
    }


    public List<AnswerEntity> getAnswers() {
        return answers;
    }

    public void setAnswers(List<AnswerEntity> answers) {
        this.answers = answers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem_id
     *
     * @return the value of problem.problem_id
     * @mbg.generated
     */
    public String getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem_id
     *
     * @param problemId the value for problem.problem_id
     * @mbg.generated
     */
    public void setProblemId(String problemId) {
        this.problemId = problemId == null ? null : problemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.question_bank_id
     *
     * @return the value of problem.question_bank_id
     * @mbg.generated
     */
    public String getQuestionBankId() {
        return questionBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.question_bank_id
     *
     * @param questionBankId the value for problem.question_bank_id
     * @mbg.generated
     */
    public void setQuestionBankId(String questionBankId) {
        this.questionBankId = questionBankId == null ? null : questionBankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem_title
     *
     * @return the value of problem.problem_title
     * @mbg.generated
     */
    public String getProblemTitle() {
        return problemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem_title
     *
     * @param problemTitle the value for problem.problem_title
     * @mbg.generated
     */
    public void setProblemTitle(String problemTitle) {
        this.problemTitle = problemTitle == null ? null : problemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem_dimension
     *
     * @return the value of problem.problem_dimension
     * @mbg.generated
     */
    public String getProblemDimension() {
        return problemDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem_dimension
     *
     * @param problemDimension the value for problem.problem_dimension
     * @mbg.generated
     */
    public void setProblemDimension(String problemDimension) {
        this.problemDimension = problemDimension == null ? null : problemDimension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.create_time
     *
     * @return the value of problem.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.create_time
     *
     * @param createTime the value for problem.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.modify_time
     *
     * @return the value of problem.modify_time
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.modify_time
     *
     * @param modifyTime the value for problem.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.status
     *
     * @return the value of problem.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.status
     *
     * @param status the value for problem.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    private List<AnswerEntity> answerEntity;

    public List<AnswerEntity> getAnswerEntity() {
        return answerEntity;
    }

    public void setAnswerEntity(List<AnswerEntity> answerEntity) {
        this.answerEntity = answerEntity;
    }

    private List<SolutionEntity> solutionEntity;

    public List<SolutionEntity> getSolutionEntity() {
        return solutionEntity;
    }

    public void setSolutionEntity(List<SolutionEntity> solutionEntity) {
        this.solutionEntity = solutionEntity;
    }
}