package com.zhxx.service.szxt.entity;

import java.util.Date;

public class SolutionEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.solution_id
     *
     * @mbg.generated
     */
    private String solutionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.problem_id
     *
     * @mbg.generated
     */
    private String problemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.solution_content
     *
     * @mbg.generated
     */
    private String solutionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.solution_fraction
     *
     * @mbg.generated
     */
    private Integer solutionFraction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.solution_id
     *
     * @return the value of solution.solution_id
     * @mbg.generated
     */
    public String getSolutionId() {
        return solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.solution_id
     *
     * @param solutionId the value for solution.solution_id
     * @mbg.generated
     */
    public void setSolutionId(String solutionId) {
        this.solutionId = solutionId == null ? null : solutionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.problem_id
     *
     * @return the value of solution.problem_id
     * @mbg.generated
     */
    public String getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.problem_id
     *
     * @param problemId the value for solution.problem_id
     * @mbg.generated
     */
    public void setProblemId(String problemId) {
        this.problemId = problemId == null ? null : problemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.solution_content
     *
     * @return the value of solution.solution_content
     * @mbg.generated
     */
    public String getSolutionContent() {
        return solutionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.solution_content
     *
     * @param solutionContent the value for solution.solution_content
     * @mbg.generated
     */
    public void setSolutionContent(String solutionContent) {
        this.solutionContent = solutionContent == null ? null : solutionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.solution_fraction
     *
     * @return the value of solution.solution_fraction
     * @mbg.generated
     */
    public Integer getSolutionFraction() {
        return solutionFraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.solution_fraction
     *
     * @param solutionFraction the value for solution.solution_fraction
     * @mbg.generated
     */
    public void setSolutionFraction(Integer solutionFraction) {
        this.solutionFraction = solutionFraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.create_time
     *
     * @return the value of solution.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.create_time
     *
     * @param createTime the value for solution.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.modify_time
     *
     * @return the value of solution.modify_time
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.modify_time
     *
     * @param modifyTime the value for solution.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.status
     *
     * @return the value of solution.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.status
     *
     * @param status the value for solution.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}