package com.zhxx.service.szxt.entity;

import java.util.Date;
import java.util.List;

public class StageEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.stage_id
     *
     * @mbg.generated
     */
    private String stageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.stage_num
     *
     * @mbg.generated
     */
    private Integer stageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.stage_stop_time
     *
     * @mbg.generated
     */
    private Date stageStopTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.stage_content
     *
     * @mbg.generated
     */
    private String stageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage.status
     *
     * @mbg.generated
     */
    private Integer status;

    private List<StageRecordEntity> StageRecord;

    public List<StageRecordEntity> getStageRecord() {
        return StageRecord;
    }

    public void setStageRecord(List<StageRecordEntity> stageRecord) {
        StageRecord = stageRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage.stage_id
     *
     * @return the value of stage.stage_id
     * @mbg.generated
     */
    public String getStageId() {
        return stageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage.stage_id
     *
     * @param stageId the value for stage.stage_id
     * @mbg.generated
     */
    public void setStageId(String stageId) {
        this.stageId = stageId == null ? null : stageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage.task_id
     *
     * @return the value of stage.task_id
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage.task_id
     *
     * @param taskId the value for stage.task_id
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage.stage_num
     *
     * @return the value of stage.stage_num
     * @mbg.generated
     */
    public Integer getStageNum() {
        return stageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage.stage_num
     *
     * @param stageNum the value for stage.stage_num
     * @mbg.generated
     */
    public void setStageNum(Integer stageNum) {
        this.stageNum = stageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage.stage_stop_time
     *
     * @return the value of stage.stage_stop_time
     * @mbg.generated
     */
    public Date getStageStopTime() {
        return stageStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage.stage_stop_time
     *
     * @param stageStopTime the value for stage.stage_stop_time
     * @mbg.generated
     */
    public void setStageStopTime(Date stageStopTime) {
        this.stageStopTime = stageStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage.stage_content
     *
     * @return the value of stage.stage_content
     * @mbg.generated
     */
    public String getStageContent() {
        return stageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage.stage_content
     *
     * @param stageContent the value for stage.stage_content
     * @mbg.generated
     */
    public void setStageContent(String stageContent) {
        this.stageContent = stageContent == null ? null : stageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage.create_time
     *
     * @return the value of stage.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage.create_time
     *
     * @param createTime the value for stage.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage.modify_time
     *
     * @return the value of stage.modify_time
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage.modify_time
     *
     * @param modifyTime the value for stage.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage.status
     *
     * @return the value of stage.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage.status
     *
     * @param status the value for stage.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}