package com.zhxx.service.szxt.entity;

import java.util.Date;

public class StageRecordEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.stage_record_id
     *
     * @mbg.generated
     */
    private String stageRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.task_record_id
     *
     * @mbg.generated
     */
    private String taskRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.stage_id
     *
     * @mbg.generated
     */
    private String stageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.stage_record_img_path
     *
     * @mbg.generated
     */
    private String stageRecordImgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.stage_record_content
     *
     * @mbg.generated
     */
    private String stageRecordContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.stage_record_status
     *
     * @mbg.generated
     */
    private Integer stageRecordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.stage_record_evaluate
     *
     * @mbg.generated
     */
    private String stageRecordEvaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stage_record.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.stage_record_id
     *
     * @return the value of stage_record.stage_record_id
     * @mbg.generated
     */
    public String getStageRecordId() {
        return stageRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.stage_record_id
     *
     * @param stageRecordId the value for stage_record.stage_record_id
     * @mbg.generated
     */
    public void setStageRecordId(String stageRecordId) {
        this.stageRecordId = stageRecordId == null ? null : stageRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.task_record_id
     *
     * @return the value of stage_record.task_record_id
     * @mbg.generated
     */
    public String getTaskRecordId() {
        return taskRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.task_record_id
     *
     * @param taskRecordId the value for stage_record.task_record_id
     * @mbg.generated
     */
    public void setTaskRecordId(String taskRecordId) {
        this.taskRecordId = taskRecordId == null ? null : taskRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.stage_id
     *
     * @return the value of stage_record.stage_id
     * @mbg.generated
     */
    public String getStageId() {
        return stageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.stage_id
     *
     * @param stageId the value for stage_record.stage_id
     * @mbg.generated
     */
    public void setStageId(String stageId) {
        this.stageId = stageId == null ? null : stageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.stage_record_img_path
     *
     * @return the value of stage_record.stage_record_img_path
     * @mbg.generated
     */
    public String getStageRecordImgPath() {
        return stageRecordImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.stage_record_img_path
     *
     * @param stageRecordImgPath the value for stage_record.stage_record_img_path
     * @mbg.generated
     */
    public void setStageRecordImgPath(String stageRecordImgPath) {
        this.stageRecordImgPath = stageRecordImgPath == null ? null : stageRecordImgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.stage_record_content
     *
     * @return the value of stage_record.stage_record_content
     * @mbg.generated
     */
    public String getStageRecordContent() {
        return stageRecordContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.stage_record_content
     *
     * @param stageRecordContent the value for stage_record.stage_record_content
     * @mbg.generated
     */
    public void setStageRecordContent(String stageRecordContent) {
        this.stageRecordContent = stageRecordContent == null ? null : stageRecordContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.stage_record_status
     *
     * @return the value of stage_record.stage_record_status
     * @mbg.generated
     */
    public Integer getStageRecordStatus() {
        return stageRecordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.stage_record_status
     *
     * @param stageRecordStatus the value for stage_record.stage_record_status
     * @mbg.generated
     */
    public void setStageRecordStatus(Integer stageRecordStatus) {
        this.stageRecordStatus = stageRecordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.stage_record_evaluate
     *
     * @return the value of stage_record.stage_record_evaluate
     * @mbg.generated
     */
    public String getStageRecordEvaluate() {
        return stageRecordEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.stage_record_evaluate
     *
     * @param stageRecordEvaluate the value for stage_record.stage_record_evaluate
     * @mbg.generated
     */
    public void setStageRecordEvaluate(String stageRecordEvaluate) {
        this.stageRecordEvaluate = stageRecordEvaluate == null ? null : stageRecordEvaluate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.create_time
     *
     * @return the value of stage_record.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.create_time
     *
     * @param createTime the value for stage_record.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.modify_time
     *
     * @return the value of stage_record.modify_time
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.modify_time
     *
     * @param modifyTime the value for stage_record.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stage_record.status
     *
     * @return the value of stage_record.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stage_record.status
     *
     * @param status the value for stage_record.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}