package com.zhxx.service.szxt.entity;

import java.util.Date;
import java.util.List;

public class TaskRecordEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.task_record_id
     *
     * @mbg.generated
     */
    private String taskRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.task_record_status
     *
     * @mbg.generated
     */
    private Integer taskRecordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_record.status
     *
     * @mbg.generated
     */
    private Integer status;

    private String markId;

    private List<StudentEntity> studentEntities;

    private List<TaskEntity> taskEntities;

    public List<TaskEntity> getTaskEntities() {
        return taskEntities;
    }

    public void setTaskEntities(List<TaskEntity> taskEntities) {
        this.taskEntities = taskEntities;
    }

    public List<StudentEntity> getStudentEntities() {
        return studentEntities;
    }

    public void setStudentEntities(List<StudentEntity> studentEntities) {
        this.studentEntities = studentEntities;
    }

    public String getMarkId() {
        return markId;
    }

    public void setMarkId(String markId) {
        this.markId = markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.task_record_id
     *
     * @return the value of task_record.task_record_id
     * @mbg.generated
     */
    public String getTaskRecordId() {
        return taskRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.task_record_id
     *
     * @param taskRecordId the value for task_record.task_record_id
     * @mbg.generated
     */
    public void setTaskRecordId(String taskRecordId) {
        this.taskRecordId = taskRecordId == null ? null : taskRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.student_id
     *
     * @return the value of task_record.student_id
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.student_id
     *
     * @param studentId the value for task_record.student_id
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.task_id
     *
     * @return the value of task_record.task_id
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.task_id
     *
     * @param taskId the value for task_record.task_id
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.task_record_status
     *
     * @return the value of task_record.task_record_status
     * @mbg.generated
     */
    public Integer getTaskRecordStatus() {
        return taskRecordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.task_record_status
     *
     * @param taskRecordStatus the value for task_record.task_record_status
     * @mbg.generated
     */
    public void setTaskRecordStatus(Integer taskRecordStatus) {
        this.taskRecordStatus = taskRecordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.create_time
     *
     * @return the value of task_record.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.create_time
     *
     * @param createTime the value for task_record.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.modify_time
     *
     * @return the value of task_record.modify_time
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.modify_time
     *
     * @param modifyTime the value for task_record.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_record.status
     *
     * @return the value of task_record.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_record.status
     *
     * @param status the value for task_record.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}