package com.zhxx.service.szxt.entity;

import java.util.Date;
import java.util.List;

public class TaskEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_name
     *
     * @mbg.generated
     */
    private String taskName;

    private String Publisher;  //发布方
    private String identification;  //识别身份
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.dimension_id
     *
     * @mbg.generated
     */
    private String dimensionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_stop_time
     *
     * @mbg.generated
     */
    private Date taskStopTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_status
     *
     * @mbg.generated
     */
    private Integer taskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbg.generated
     */
    private Integer status;

    private Integer stageAll;

    private String userName;

    private List<StageEntity> stageEntities;

    public String getPublisher() {
        return Publisher;
    }

    public void setPublisher(String publisher) {
        Publisher = publisher;
    }

    public String getIdentification() {
        return identification;
    }

    public void setIdentification(String identification) {
        this.identification = identification;
    }

    public List<StageEntity> getStageEntities() {
        return stageEntities;
    }

    public void setStageEntities(List<StageEntity> stageEntities) {
        this.stageEntities = stageEntities;
    }

    private List<DimensionEntity> dimensionEntities;

    public List<DimensionEntity> getDimensionEntities() {
        return dimensionEntities;
    }

    public void setDimensionEntities(List<DimensionEntity> dimensionEntities) {
        this.dimensionEntities = dimensionEntities;
    }

    private Integer pageNum;

    private Integer pageSize;

    private String state;

    private List<StageEntity> stageEntityList;

    public List<StageEntity> getStageEntityList() {
        return stageEntityList;
    }

    public void setStageEntityList(List<StageEntity> stageEntityList) {
        this.stageEntityList = stageEntityList;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getPageNum() {
        return pageNum;
    }

    public void setPageNum(Integer pageNum) {
        this.pageNum = pageNum;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Integer getStageAll() {
        return stageAll;
    }

    public void setStageAll(Integer stageAll) {
        this.stageAll = stageAll;
    }

    private String dimensionName;


    public String getDimensionName() {
        return dimensionName;
    }

    public void setDimensionName(String dimensionName) {
        this.dimensionName = dimensionName;
    }

    public String getMarkId() {
        return markId;
    }

    public void setMarkId(String markId) {
        this.markId = markId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     * @mbg.generated
     */

    private String markId;

    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_name
     *
     * @return the value of task.task_name
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_name
     *
     * @param taskName the value for task.task_name
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.dimension_id
     *
     * @return the value of task.dimension_id
     * @mbg.generated
     */
    public String getDimensionId() {
        return dimensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.dimension_id
     *
     * @param dimensionId the value for task.dimension_id
     * @mbg.generated
     */
    public void setDimensionId(String dimensionId) {
        this.dimensionId = dimensionId == null ? null : dimensionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_stop_time
     *
     * @return the value of task.task_stop_time
     * @mbg.generated
     */
    public Date getTaskStopTime() {
        return taskStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_stop_time
     *
     * @param taskStopTime the value for task.task_stop_time
     * @mbg.generated
     */
    public void setTaskStopTime(Date taskStopTime) {
        this.taskStopTime = taskStopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.user_id
     *
     * @return the value of task.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.user_id
     *
     * @param userId the value for task.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_status
     *
     * @return the value of task.task_status
     * @mbg.generated
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_status
     *
     * @param taskStatus the value for task.task_status
     * @mbg.generated
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param createTime the value for task.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.modify_time
     *
     * @return the value of task.modify_time
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.modify_time
     *
     * @param modifyTime the value for task.modify_time
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}