package com.zhxx.service.szxt.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TeacherPrizeEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.leading
     *
     * @mbg.generated
     */
    private String leading;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.participant
     *
     * @mbg.generated
     */
    private String participant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.awards received
     *
     * @mbg.generated
     */
    private String awardsReceived;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.awarding_unit
     *
     * @mbg.generated
     */
    private String awardingUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.certificate_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date certificateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.create_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_prize.modify_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date modifyTime;
    private String[] picId;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.id
     *
     * @return the value of teacher_prize.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.id
     *
     * @param id the value for teacher_prize.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.product_name
     *
     * @return the value of teacher_prize.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.product_name
     *
     * @param productName the value for teacher_prize.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.leading
     *
     * @return the value of teacher_prize.leading
     *
     * @mbg.generated
     */
    public String getLeading() {
        return leading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.leading
     *
     * @param leading the value for teacher_prize.leading
     *
     * @mbg.generated
     */
    public void setLeading(String leading) {
        this.leading = leading == null ? null : leading.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.participant
     *
     * @return the value of teacher_prize.participant
     *
     * @mbg.generated
     */
    public String getParticipant() {
        return participant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.participant
     *
     * @param participant the value for teacher_prize.participant
     *
     * @mbg.generated
     */
    public void setParticipant(String participant) {
        this.participant = participant == null ? null : participant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.awards received
     *
     * @return the value of teacher_prize.awards received
     *
     * @mbg.generated
     */
    public String getAwardsReceived() {
        return awardsReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.awards received
     *
     * @param awardsReceived the value for teacher_prize.awards received
     *
     * @mbg.generated
     */
    public void setAwardsReceived(String awardsReceived) {
        this.awardsReceived = awardsReceived == null ? null : awardsReceived.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.awarding_unit
     *
     * @return the value of teacher_prize.awarding_unit
     *
     * @mbg.generated
     */
    public String getAwardingUnit() {
        return awardingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.awarding_unit
     *
     * @param awardingUnit the value for teacher_prize.awarding_unit
     *
     * @mbg.generated
     */
    public void setAwardingUnit(String awardingUnit) {
        this.awardingUnit = awardingUnit == null ? null : awardingUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.level
     *
     * @return the value of teacher_prize.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.level
     *
     * @param level the value for teacher_prize.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.certificate_date
     *
     * @return the value of teacher_prize.certificate_date
     *
     * @mbg.generated
     */
    public Date getCertificateDate() {
        return certificateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.certificate_date
     *
     * @param certificateDate the value for teacher_prize.certificate_date
     *
     * @mbg.generated
     */
    public void setCertificateDate(Date certificateDate) {
        this.certificateDate = certificateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.operator
     *
     * @return the value of teacher_prize.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.operator
     *
     * @param operator the value for teacher_prize.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.create_time
     *
     * @return the value of teacher_prize.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.create_time
     *
     * @param createTime the value for teacher_prize.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_prize.modify_time
     *
     * @return the value of teacher_prize.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_prize.modify_time
     *
     * @param modifyTime the value for teacher_prize.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	public String[] getPicId() {
		return picId;
	}

	public void setPicId(String[] picId) {
		this.picId = picId;
	}
    
}