package com.zhxx.service.szxt.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TeacherUserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.teacher_id
     *
     * @mbg.generated
     */
	private String id;
    private String teacherId;
    private String permissionId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.teacher_phone_number
     *
     * @mbg.generated
     */
    private String teacherPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.teacher_email
     *
     * @mbg.generated
     */
    private String teacherEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.create_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.modify_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.teacher_no
     *
     * @mbg.generated
     */
    private String teacherNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.teacher_openid
     *
     * @mbg.generated
     */
    private String teacherOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.college
     *
     * @mbg.generated
     */
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_user.major
     *
     * @mbg.generated
     */
    private String major;
    
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date allowCheckTime;
    
    
    //统计数量
    private String paperCount;
    private String writingsCount;
    private String projectCount;
    private String concludingCount;
    private String horizontalCount;
    private String prizeCount;
    private String patentCount;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.teacher_id
     *
     * @return the value of teacher_user.teacher_id
     *
     * @mbg.generated
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.teacher_id
     *
     * @param teacherId the value for teacher_user.teacher_id
     *
     * @mbg.generated
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.user_name
     *
     * @return the value of teacher_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.user_name
     *
     * @param userName the value for teacher_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.password
     *
     * @return the value of teacher_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.password
     *
     * @param password the value for teacher_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.teacher_phone_number
     *
     * @return the value of teacher_user.teacher_phone_number
     *
     * @mbg.generated
     */
    public String getTeacherPhoneNumber() {
        return teacherPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.teacher_phone_number
     *
     * @param teacherPhoneNumber the value for teacher_user.teacher_phone_number
     *
     * @mbg.generated
     */
    public void setTeacherPhoneNumber(String teacherPhoneNumber) {
        this.teacherPhoneNumber = teacherPhoneNumber == null ? null : teacherPhoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.teacher_email
     *
     * @return the value of teacher_user.teacher_email
     *
     * @mbg.generated
     */
    public String getTeacherEmail() {
        return teacherEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.teacher_email
     *
     * @param teacherEmail the value for teacher_user.teacher_email
     *
     * @mbg.generated
     */
    public void setTeacherEmail(String teacherEmail) {
        this.teacherEmail = teacherEmail == null ? null : teacherEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.create_time
     *
     * @return the value of teacher_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.create_time
     *
     * @param createTime the value for teacher_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.modify_time
     *
     * @return the value of teacher_user.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.modify_time
     *
     * @param modifyTime the value for teacher_user.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.status
     *
     * @return the value of teacher_user.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.status
     *
     * @param status the value for teacher_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.teacher_no
     *
     * @return the value of teacher_user.teacher_no
     *
     * @mbg.generated
     */
    public String getTeacherNo() {
        return teacherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.teacher_no
     *
     * @param teacherNo the value for teacher_user.teacher_no
     *
     * @mbg.generated
     */
    public void setTeacherNo(String teacherNo) {
        this.teacherNo = teacherNo == null ? null : teacherNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.teacher_openid
     *
     * @return the value of teacher_user.teacher_openid
     *
     * @mbg.generated
     */
    public String getTeacherOpenid() {
        return teacherOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.teacher_openid
     *
     * @param teacherOpenid the value for teacher_user.teacher_openid
     *
     * @mbg.generated
     */
    public void setTeacherOpenid(String teacherOpenid) {
        this.teacherOpenid = teacherOpenid == null ? null : teacherOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.college
     *
     * @return the value of teacher_user.college
     *
     * @mbg.generated
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.college
     *
     * @param college the value for teacher_user.college
     *
     * @mbg.generated
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_user.major
     *
     * @return the value of teacher_user.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }
    
    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
    
	public String getPermissionId() {
		return permissionId;
	}

	public void setPermissionId(String permissionId) {
		this.permissionId = permissionId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_user.major
     *
     * @param major the value for teacher_user.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

	public Date getAllowCheckTime() {
		return allowCheckTime;
	}

	public void setAllowCheckTime(Date allowCheckTime) {
		this.allowCheckTime = allowCheckTime;
	}

	public String getPaperCount() {
		return paperCount;
	}

	public void setPaperCount(String paperCount) {
		this.paperCount = paperCount;
	}

	public String getWritingsCount() {
		return writingsCount;
	}

	public void setWritingsCount(String writingsCount) {
		this.writingsCount = writingsCount;
	}

	public String getProjectCount() {
		return projectCount;
	}

	public void setProjectCount(String projectCount) {
		this.projectCount = projectCount;
	}

	public String getConcludingCount() {
		return concludingCount;
	}

	public void setConcludingCount(String concludingCount) {
		this.concludingCount = concludingCount;
	}

	public String getHorizontalCount() {
		return horizontalCount;
	}

	public void setHorizontalCount(String horizontalCount) {
		this.horizontalCount = horizontalCount;
	}

	public String getPrizeCount() {
		return prizeCount;
	}

	public void setPrizeCount(String prizeCount) {
		this.prizeCount = prizeCount;
	}

	public String getPatentCount() {
		return patentCount;
	}

	public void setPatentCount(String patentCount) {
		this.patentCount = patentCount;
	}
    
}