package com.zhxx.service.szxt.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TeacherConcludingEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.project_no
     *
     * @mbg.generated
     */
    private String projectNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.participant
     *
     * @mbg.generated
     */
    private String participant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.project_category
     *
     * @mbg.generated
     */
    private String projectCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.project_level
     *
     * @mbg.generated
     */
    private String projectLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.project_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date projectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.research_funding
     *
     * @mbg.generated
     */
    private String researchFunding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.concluding_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date concludingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.create_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_concluding.modify_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date modifyTime;
    private String[] picId;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.id
     *
     * @return the value of teacher_concluding.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.id
     *
     * @param id the value for teacher_concluding.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.project_no
     *
     * @return the value of teacher_concluding.project_no
     *
     * @mbg.generated
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.project_no
     *
     * @param projectNo the value for teacher_concluding.project_no
     *
     * @mbg.generated
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.project_name
     *
     * @return the value of teacher_concluding.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.project_name
     *
     * @param projectName the value for teacher_concluding.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.host
     *
     * @return the value of teacher_concluding.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.host
     *
     * @param host the value for teacher_concluding.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.participant
     *
     * @return the value of teacher_concluding.participant
     *
     * @mbg.generated
     */
    public String getParticipant() {
        return participant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.participant
     *
     * @param participant the value for teacher_concluding.participant
     *
     * @mbg.generated
     */
    public void setParticipant(String participant) {
        this.participant = participant == null ? null : participant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.source
     *
     * @return the value of teacher_concluding.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.source
     *
     * @param source the value for teacher_concluding.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.project_category
     *
     * @return the value of teacher_concluding.project_category
     *
     * @mbg.generated
     */
    public String getProjectCategory() {
        return projectCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.project_category
     *
     * @param projectCategory the value for teacher_concluding.project_category
     *
     * @mbg.generated
     */
    public void setProjectCategory(String projectCategory) {
        this.projectCategory = projectCategory == null ? null : projectCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.project_level
     *
     * @return the value of teacher_concluding.project_level
     *
     * @mbg.generated
     */
    public String getProjectLevel() {
        return projectLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.project_level
     *
     * @param projectLevel the value for teacher_concluding.project_level
     *
     * @mbg.generated
     */
    public void setProjectLevel(String projectLevel) {
        this.projectLevel = projectLevel == null ? null : projectLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.project_time
     *
     * @return the value of teacher_concluding.project_time
     *
     * @mbg.generated
     */
    public Date getProjectTime() {
        return projectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.project_time
     *
     * @param projectTime the value for teacher_concluding.project_time
     *
     * @mbg.generated
     */
    public void setProjectTime(Date projectTime) {
        this.projectTime = projectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.research_funding
     *
     * @return the value of teacher_concluding.research_funding
     *
     * @mbg.generated
     */
    public String getResearchFunding() {
        return researchFunding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.research_funding
     *
     * @param researchFunding the value for teacher_concluding.research_funding
     *
     * @mbg.generated
     */
    public void setResearchFunding(String researchFunding) {
        this.researchFunding = researchFunding == null ? null : researchFunding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.remarks
     *
     * @return the value of teacher_concluding.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.remarks
     *
     * @param remarks the value for teacher_concluding.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.concluding_time
     *
     * @return the value of teacher_concluding.concluding_time
     *
     * @mbg.generated
     */
    public Date getConcludingTime() {
        return concludingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.concluding_time
     *
     * @param concludingTime the value for teacher_concluding.concluding_time
     *
     * @mbg.generated
     */
    public void setConcludingTime(Date concludingTime) {
        this.concludingTime = concludingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.operator
     *
     * @return the value of teacher_concluding.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.operator
     *
     * @param operator the value for teacher_concluding.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.create_time
     *
     * @return the value of teacher_concluding.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.create_time
     *
     * @param createTime the value for teacher_concluding.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_concluding.modify_time
     *
     * @return the value of teacher_concluding.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_concluding.modify_time
     *
     * @param modifyTime the value for teacher_concluding.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	public String[] getPicId() {
		return picId;
	}

	public void setPicId(String[] picId) {
		this.picId = picId;
	}
    
}