package com.zhxx.service.szxt.entity;

public class TeacherOutputPicRelateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_output_pic_relate.output_id
     *
     * @mbg.generated
     */
    private String outputId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_output_pic_relate.pic_id
     *
     * @mbg.generated
     */
    private String picId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_output_pic_relate.output_id
     *
     * @return the value of teacher_output_pic_relate.output_id
     *
     * @mbg.generated
     */
    public String getOutputId() {
        return outputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_output_pic_relate.output_id
     *
     * @param outputId the value for teacher_output_pic_relate.output_id
     *
     * @mbg.generated
     */
    public void setOutputId(String outputId) {
        this.outputId = outputId == null ? null : outputId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_output_pic_relate.pic_id
     *
     * @return the value of teacher_output_pic_relate.pic_id
     *
     * @mbg.generated
     */
    public String getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_output_pic_relate.pic_id
     *
     * @param picId the value for teacher_output_pic_relate.pic_id
     *
     * @mbg.generated
     */
    public void setPicId(String picId) {
        this.picId = picId == null ? null : picId.trim();
    }
}