package com.zhxx.service.szxt.entity;

public class TeacherResearchSectionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_research_section.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_research_section.parentId
     *
     * @mbg.generated
     */
    private Long parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_research_section.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_research_section.css
     *
     * @mbg.generated
     */
    private String css;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_research_section.href
     *
     * @mbg.generated
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_research_section.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_research_section.permission
     *
     * @mbg.generated
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_research_section.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_research_section.id
     *
     * @return the value of teacher_research_section.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_research_section.id
     *
     * @param id the value for teacher_research_section.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_research_section.parentId
     *
     * @return the value of teacher_research_section.parentId
     *
     * @mbg.generated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_research_section.parentId
     *
     * @param parentid the value for teacher_research_section.parentId
     *
     * @mbg.generated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_research_section.name
     *
     * @return the value of teacher_research_section.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_research_section.name
     *
     * @param name the value for teacher_research_section.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_research_section.css
     *
     * @return the value of teacher_research_section.css
     *
     * @mbg.generated
     */
    public String getCss() {
        return css;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_research_section.css
     *
     * @param css the value for teacher_research_section.css
     *
     * @mbg.generated
     */
    public void setCss(String css) {
        this.css = css == null ? null : css.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_research_section.href
     *
     * @return the value of teacher_research_section.href
     *
     * @mbg.generated
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_research_section.href
     *
     * @param href the value for teacher_research_section.href
     *
     * @mbg.generated
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_research_section.type
     *
     * @return the value of teacher_research_section.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_research_section.type
     *
     * @param type the value for teacher_research_section.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_research_section.permission
     *
     * @return the value of teacher_research_section.permission
     *
     * @mbg.generated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_research_section.permission
     *
     * @param permission the value for teacher_research_section.permission
     *
     * @mbg.generated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_research_section.sort
     *
     * @return the value of teacher_research_section.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_research_section.sort
     *
     * @param sort the value for teacher_research_section.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}