package com.zhxx.service.szxt.entity;

public class TeacherRoleEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_role.teacher_role_id
     *
     * @mbg.generated
     */
    private String teacherRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_role.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_role.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_role.teacher_role_id
     *
     * @return the value of teacher_role.teacher_role_id
     * @mbg.generated
     */
    public String getTeacherRoleId() {
        return teacherRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_role.teacher_role_id
     *
     * @param teacherRoleId the value for teacher_role.teacher_role_id
     * @mbg.generated
     */
    public void setTeacherRoleId(String teacherRoleId) {
        this.teacherRoleId = teacherRoleId == null ? null : teacherRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_role.user_id
     *
     * @return the value of teacher_role.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_role.user_id
     *
     * @param userId the value for teacher_role.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_role.role_id
     *
     * @return the value of teacher_role.role_id
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_role.role_id
     *
     * @param roleId the value for teacher_role.role_id
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}