package com.zhxx.service.szxt.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TeacherWritingsEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.press_name
     *
     * @mbg.generated
     */
    private String pressName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.press_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date pressDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.author_rank
     *
     * @mbg.generated
     */
    private String authorRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.categories
     *
     * @mbg.generated
     */
    private String categories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.compilation_form
     *
     * @mbg.generated
     */
    private String compilationForm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.bool_no
     *
     * @mbg.generated
     */
    private String bookNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.total_words
     *
     * @mbg.generated
     */
    private String totalWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.create_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_writings.modify_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date modifyTime;
    private String[] picId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.id
     *
     * @return the value of teacher_writings.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.id
     *
     * @param id the value for teacher_writings.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.title
     *
     * @return the value of teacher_writings.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.title
     *
     * @param title the value for teacher_writings.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.author
     *
     * @return the value of teacher_writings.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.author
     *
     * @param author the value for teacher_writings.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.press_name
     *
     * @return the value of teacher_writings.press_name
     *
     * @mbg.generated
     */
    public String getPressName() {
        return pressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.press_name
     *
     * @param pressName the value for teacher_writings.press_name
     *
     * @mbg.generated
     */
    public void setPressName(String pressName) {
        this.pressName = pressName == null ? null : pressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.press_date
     *
     * @return the value of teacher_writings.press_date
     *
     * @mbg.generated
     */
    public Date getPressDate() {
        return pressDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.press_date
     *
     * @param pressDate the value for teacher_writings.press_date
     *
     * @mbg.generated
     */
    public void setPressDate(Date pressDate) {
        this.pressDate = pressDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.author_rank
     *
     * @return the value of teacher_writings.author_rank
     *
     * @mbg.generated
     */
    public String getAuthorRank() {
        return authorRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.author_rank
     *
     * @param authorRank the value for teacher_writings.author_rank
     *
     * @mbg.generated
     */
    public void setAuthorRank(String authorRank) {
        this.authorRank = authorRank == null ? null : authorRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.categories
     *
     * @return the value of teacher_writings.categories
     *
     * @mbg.generated
     */
    public String getCategories() {
        return categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.categories
     *
     * @param categories the value for teacher_writings.categories
     *
     * @mbg.generated
     */
    public void setCategories(String categories) {
        this.categories = categories == null ? null : categories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.remarks
     *
     * @return the value of teacher_writings.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.remarks
     *
     * @param remarks the value for teacher_writings.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.compilation_form
     *
     * @return the value of teacher_writings.compilation_form
     *
     * @mbg.generated
     */
    public String getCompilationForm() {
        return compilationForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.compilation_form
     *
     * @param compilationForm the value for teacher_writings.compilation_form
     *
     * @mbg.generated
     */
    public void setCompilationForm(String compilationForm) {
        this.compilationForm = compilationForm == null ? null : compilationForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.bool_no
     *
     * @return the value of teacher_writings.bool_no
     *
     * @mbg.generated
     */
    public String getBoolNo() {
        return bookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.bool_no
     *
     * @param boolNo the value for teacher_writings.bool_no
     *
     * @mbg.generated
     */
    public void setBoolNo(String bookNo) {
        this.bookNo = bookNo == null ? null : bookNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.total_words
     *
     * @return the value of teacher_writings.total_words
     *
     * @mbg.generated
     */
    public String getTotalWords() {
        return totalWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.total_words
     *
     * @param totalWords the value for teacher_writings.total_words
     *
     * @mbg.generated
     */
    public void setTotalWords(String totalWords) {
        this.totalWords = totalWords == null ? null : totalWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.operator
     *
     * @return the value of teacher_writings.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.operator
     *
     * @param operator the value for teacher_writings.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.create_time
     *
     * @return the value of teacher_writings.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.create_time
     *
     * @param createTime the value for teacher_writings.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_writings.modify_time
     *
     * @return the value of teacher_writings.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_writings.modify_time
     *
     * @param modifyTime the value for teacher_writings.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	public String getBookNo() {
		return bookNo;
	}

	public void setBookNo(String bookNo) {
		this.bookNo = bookNo;
	}

	public String[] getPicId() {
		return picId;
	}

	public void setPicId(String[] picId) {
		this.picId = picId;
	}
    
}