package com.zhxx.service.szxt.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TeacherPatentEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.designer
     *
     * @mbg.generated
     */
    private String designer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.ranking
     *
     * @mbg.generated
     */
    private String ranking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.patent_person
     *
     * @mbg.generated
     */
    private String patentPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.right_categories
     *
     * @mbg.generated
     */
    private String rightCategories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.applying_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date applyingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.anno_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date annoDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.patent_number
     *
     * @mbg.generated
     */
    private String patentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.patent_name
     *
     * @mbg.generated
     */
    private String patentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.create_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_patent.modify_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date modifyTime;
    private String[] picId;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.id
     *
     * @return the value of teacher_patent.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.id
     *
     * @param id the value for teacher_patent.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.designer
     *
     * @return the value of teacher_patent.designer
     *
     * @mbg.generated
     */
    public String getDesigner() {
        return designer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.designer
     *
     * @param designer the value for teacher_patent.designer
     *
     * @mbg.generated
     */
    public void setDesigner(String designer) {
        this.designer = designer == null ? null : designer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.ranking
     *
     * @return the value of teacher_patent.ranking
     *
     * @mbg.generated
     */
    public String getRanking() {
        return ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.ranking
     *
     * @param ranking the value for teacher_patent.ranking
     *
     * @mbg.generated
     */
    public void setRanking(String ranking) {
        this.ranking = ranking == null ? null : ranking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.patent_person
     *
     * @return the value of teacher_patent.patent_person
     *
     * @mbg.generated
     */
    public String getPatentPerson() {
        return patentPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.patent_person
     *
     * @param patentPerson the value for teacher_patent.patent_person
     *
     * @mbg.generated
     */
    public void setPatentPerson(String patentPerson) {
        this.patentPerson = patentPerson == null ? null : patentPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.right_categories
     *
     * @return the value of teacher_patent.right_categories
     *
     * @mbg.generated
     */
    public String getRightCategories() {
        return rightCategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.right_categories
     *
     * @param rightCategories the value for teacher_patent.right_categories
     *
     * @mbg.generated
     */
    public void setRightCategories(String rightCategories) {
        this.rightCategories = rightCategories == null ? null : rightCategories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.applying_date
     *
     * @return the value of teacher_patent.applying_date
     *
     * @mbg.generated
     */
    public Date getApplyingDate() {
        return applyingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.applying_date
     *
     * @param applyingDate the value for teacher_patent.applying_date
     *
     * @mbg.generated
     */
    public void setApplyingDate(Date applyingDate) {
        this.applyingDate = applyingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.anno_date
     *
     * @return the value of teacher_patent.anno_date
     *
     * @mbg.generated
     */
    public Date getAnnoDate() {
        return annoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.anno_date
     *
     * @param annoDate the value for teacher_patent.anno_date
     *
     * @mbg.generated
     */
    public void setAnnoDate(Date annoDate) {
        this.annoDate = annoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.patent_number
     *
     * @return the value of teacher_patent.patent_number
     *
     * @mbg.generated
     */
    public String getPatentNumber() {
        return patentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.patent_number
     *
     * @param patentNumber the value for teacher_patent.patent_number
     *
     * @mbg.generated
     */
    public void setPatentNumber(String patentNumber) {
        this.patentNumber = patentNumber == null ? null : patentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.patent_name
     *
     * @return the value of teacher_patent.patent_name
     *
     * @mbg.generated
     */
    public String getPatentName() {
        return patentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.patent_name
     *
     * @param patentName the value for teacher_patent.patent_name
     *
     * @mbg.generated
     */
    public void setPatentName(String patentName) {
        this.patentName = patentName == null ? null : patentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.operator
     *
     * @return the value of teacher_patent.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.operator
     *
     * @param operator the value for teacher_patent.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.create_time
     *
     * @return the value of teacher_patent.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.create_time
     *
     * @param createTime the value for teacher_patent.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_patent.modify_time
     *
     * @return the value of teacher_patent.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_patent.modify_time
     *
     * @param modifyTime the value for teacher_patent.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	public String[] getPicId() {
		return picId;
	}

	public void setPicId(String[] picId) {
		this.picId = picId;
	}
    
}