package com.zhxx.service.szxt.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TeacherPaperEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.journal_name
     *
     * @mbg.generated
     */
    private String journalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.journal_no
     *
     * @mbg.generated
     */
    private String journalNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.organizer
     *
     * @mbg.generated
     */
    private String organizer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.publish_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date publishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.journal_level
     *
     * @mbg.generated
     */
    private String journalLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.page
     *
     * @mbg.generated
     */
    private String page;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.author_rank
     *
     * @mbg.generated
     */
    private String authorRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.categories
     *
     * @mbg.generated
     */
    private String categories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.create_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_paper.modify_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date modifyTime;
    
    private String[] picId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.id
     *
     * @return the value of teacher_paper.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.id
     *
     * @param id the value for teacher_paper.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.title
     *
     * @return the value of teacher_paper.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.title
     *
     * @param title the value for teacher_paper.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.author
     *
     * @return the value of teacher_paper.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.author
     *
     * @param author the value for teacher_paper.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.journal_name
     *
     * @return the value of teacher_paper.journal_name
     *
     * @mbg.generated
     */
    public String getJournalName() {
        return journalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.journal_name
     *
     * @param journalName the value for teacher_paper.journal_name
     *
     * @mbg.generated
     */
    public void setJournalName(String journalName) {
        this.journalName = journalName == null ? null : journalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.journal_no
     *
     * @return the value of teacher_paper.journal_no
     *
     * @mbg.generated
     */
    public String getJournalNo() {
        return journalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.journal_no
     *
     * @param journalNo the value for teacher_paper.journal_no
     *
     * @mbg.generated
     */
    public void setJournalNo(String journalNo) {
        this.journalNo = journalNo == null ? null : journalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.organizer
     *
     * @return the value of teacher_paper.organizer
     *
     * @mbg.generated
     */
    public String getOrganizer() {
        return organizer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.organizer
     *
     * @param organizer the value for teacher_paper.organizer
     *
     * @mbg.generated
     */
    public void setOrganizer(String organizer) {
        this.organizer = organizer == null ? null : organizer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.publish_date
     *
     * @return the value of teacher_paper.publish_date
     *
     * @mbg.generated
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.publish_date
     *
     * @param publishDate the value for teacher_paper.publish_date
     *
     * @mbg.generated
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.journal_level
     *
     * @return the value of teacher_paper.journal_level
     *
     * @mbg.generated
     */
    public String getJournalLevel() {
        return journalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.journal_level
     *
     * @param journalLevel the value for teacher_paper.journal_level
     *
     * @mbg.generated
     */
    public void setJournalLevel(String journalLevel) {
        this.journalLevel = journalLevel == null ? null : journalLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.page
     *
     * @return the value of teacher_paper.page
     *
     * @mbg.generated
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.page
     *
     * @param page the value for teacher_paper.page
     *
     * @mbg.generated
     */
    public void setPage(String page) {
        this.page = page == null ? null : page.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.author_rank
     *
     * @return the value of teacher_paper.author_rank
     *
     * @mbg.generated
     */
    public String getAuthorRank() {
        return authorRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.author_rank
     *
     * @param authorRank the value for teacher_paper.author_rank
     *
     * @mbg.generated
     */
    public void setAuthorRank(String authorRank) {
        this.authorRank = authorRank == null ? null : authorRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.categories
     *
     * @return the value of teacher_paper.categories
     *
     * @mbg.generated
     */
    public String getCategories() {
        return categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.categories
     *
     * @param categories the value for teacher_paper.categories
     *
     * @mbg.generated
     */
    public void setCategories(String categories) {
        this.categories = categories == null ? null : categories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.remarks
     *
     * @return the value of teacher_paper.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.remarks
     *
     * @param remarks the value for teacher_paper.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.operator
     *
     * @return the value of teacher_paper.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.operator
     *
     * @param operator the value for teacher_paper.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.create_time
     *
     * @return the value of teacher_paper.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.create_time
     *
     * @param createTime the value for teacher_paper.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_paper.modify_time
     *
     * @return the value of teacher_paper.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_paper.modify_time
     *
     * @param modifyTime the value for teacher_paper.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	public String[] getPicId() {
		return picId;
	}

	public void setPicId(String[] picId) {
		this.picId = picId;
	}
    
}