package com.zhxx.service.szxt.entity;

public class TeacherStudentRelateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_student_relate.teacher_id
     *
     * @mbg.generated
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_student_relate.student_id
     *
     * @mbg.generated
     */
    private String studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_student_relate.teacher_id
     *
     * @return the value of teacher_student_relate.teacher_id
     *
     * @mbg.generated
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_student_relate.teacher_id
     *
     * @param teacherId the value for teacher_student_relate.teacher_id
     *
     * @mbg.generated
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_student_relate.student_id
     *
     * @return the value of teacher_student_relate.student_id
     *
     * @mbg.generated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_student_relate.student_id
     *
     * @param studentId the value for teacher_student_relate.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }
}