package com.zhxx.service.szxt.entity;

import java.util.Date;

public class WechatParentEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_parent.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_parent.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_parent.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_parent.student_no
     *
     * @mbg.generated
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_parent.parent_name
     *
     * @mbg.generated
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_parent.relationship
     *
     * @mbg.generated
     */
    private String relationship;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_parent.binding_code
     *
     * @mbg.generated
     */
    private String bindingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_parent.parent_phone
     *
     * @mbg.generated
     */
    private String parentPhone;

    private String identification;

    private String studentId;

    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getIdentification() {
        return identification;
    }

    public void setIdentification(String identification) {
        this.identification = identification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_parent.parent_id
     *
     * @return the value of wechat_parent.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_parent.parent_id
     *
     * @param parentId the value for wechat_parent.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_parent.open_id
     *
     * @return the value of wechat_parent.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_parent.open_id
     *
     * @param openId the value for wechat_parent.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_parent.create_time
     *
     * @return the value of wechat_parent.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_parent.create_time
     *
     * @param createTime the value for wechat_parent.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_parent.student_no
     *
     * @return the value of wechat_parent.student_no
     *
     * @mbg.generated
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_parent.student_no
     *
     * @param studentNo the value for wechat_parent.student_no
     *
     * @mbg.generated
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_parent.parent_name
     *
     * @return the value of wechat_parent.parent_name
     *
     * @mbg.generated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_parent.parent_name
     *
     * @param parentName the value for wechat_parent.parent_name
     *
     * @mbg.generated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_parent.relationship
     *
     * @return the value of wechat_parent.relationship
     *
     * @mbg.generated
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_parent.relationship
     *
     * @param relationship the value for wechat_parent.relationship
     *
     * @mbg.generated
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship == null ? null : relationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_parent.binding_code
     *
     * @return the value of wechat_parent.binding_code
     *
     * @mbg.generated
     */
    public String getBindingCode() {
        return bindingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_parent.binding_code
     *
     * @param bindingCode the value for wechat_parent.binding_code
     *
     * @mbg.generated
     */
    public void setBindingCode(String bindingCode) {
        this.bindingCode = bindingCode == null ? null : bindingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_parent.parent_phone
     *
     * @return the value of wechat_parent.parent_phone
     *
     * @mbg.generated
     */
    public String getParentPhone() {
        return parentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_parent.parent_phone
     *
     * @param parentPhone the value for wechat_parent.parent_phone
     *
     * @mbg.generated
     */
    public void setParentPhone(String parentPhone) {
        this.parentPhone = parentPhone == null ? null : parentPhone.trim();
    }
}